# Generated by Django 4.1.4 on 2022-12-16 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trello_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
