# Generated by Django 4.1.4 on 2022-12-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0002_board_users"),
    ]

    operations = [
        migrations.RenameModel(old_name="Comments", new_name="Comment",),
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(upload_to="static/board_images"),
        ),
    ]
