# Generated by Django 4.1.4 on 2022-12-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0003_rename_comments_comment_alter_board_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="CardMarks", new_name="CardMark",),
    ]
