# Generated by Django 4.1.4 on 2022-12-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0004_rename_cardmarks_cardmark"),
    ]

    operations = [
        migrations.RemoveField(model_name="cardmark", name="text",),
        migrations.RemoveField(model_name="checklist", name="not_done",),
        migrations.AddField(
            model_name="cardmark",
            name="card",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="trello_app.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checklist",
            name="card",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklists",
                to="trello_app.card",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checklist",
            name="task",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
