# Generated by Django 4.1.4 on 2022-12-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0006_remove_checklist_done_checklistitems"),
    ]

    operations = [
        migrations.RenameModel(old_name="CheckListItems", new_name="CheckListItem",),
    ]
