# Generated by Django 4.1.4 on 2022-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0007_rename_checklistitems_checklistitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="checklist", name="task",),
        migrations.AddField(
            model_name="checklist",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="task",
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
