# Generated by Django 4.1.4 on 2022-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0009_cardmark_text_comment_author_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmark",
            name="text",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
