# Generated by Django 4.1.4 on 2022-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0010_alter_cardmark_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmark",
            name="color",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
