# Generated by Django 4.1.4 on 2022-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0011_alter_cardmark_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
