# Generated by Django 4.1.4 on 2022-12-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trello_app", "0013_alter_comment_created_at_alter_list_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="end_date",
            field=models.DateField(default=True),
            preserve_default=False,
        ),
    ]
